### ISSUE TITLE
v10.9.2341.2 Issue?

### ISSUE THREAD

**Issue by Deltafox79** [DoubleLabyrinth/VisualAssist-keygen-demo#1]
Hi bro DoubleLabyrinth

On latest v**10.9.2341.2** The keygen doesn't seem to work ... am I wrong?

If insert only serial I have this dialog box :

![Immagine5](https://user-images.githubusercontent.com/2518850/65532772-b61d2900-defc-11e9-9601-12b261067eac.jpg)

After insert two line serial generate from keygen I have this error also whit internet off..

![Immagine4](https://user-images.githubusercontent.com/2518850/65532827-d1883400-defc-11e9-943e-009d49c52a00.jpg)

Regards

**Comment by DoubleLabyrinth** [comment]
You need `VisualAssist-patcher` to replace the official public key stored in `VA_X.dll` with our own public key, so that the serial key generated could really work. __This notice has been claimed in README...__

I can't publish `VisualAssist-patcher` due to DMCA. Otherwise, this repo would be banned. 
However if you want a patched `VA_X.dll`, give me a email, I'll send you one.

**Comment by Deltafox79** [comment]
> 
> 
> You need `VisualAssist-patcher` to replace the official public key stored in `VA_X.dll` with our own public key, so that the serial key generated could really work. **This notice has been claimed in README...**
> 
> I can't publish `VisualAssist-patcher` due to DMCA. Otherwise, this repo would be banned.
> However if you want a patched `VA_X.dll`, give me a email, I'll send you one.

Ah ok.. info@dfox.it

Regards

**Comment by DoubleLabyrinth** [comment]
Yes, it is protected by Armadillo. 
Dir is also correct, you can get it by the value `InstalledDir` in `HKCU\Software\Whole Tomato\Visual Assist X\VaNet16`.

**Comment by DoubleLabyrinth** [comment]
Ok, a patched VA_X.dll has been sent to you.

**Comment by Deltafox79** [comment]
So your patch Deobfuscate the armadillo protection, change rsa public key and reobfuscate or you patch inline?

Thank's for the dll...

**Comment by DoubleLabyrinth** [comment]
Yes

**Comment by DoubleLabyrinth** [comment]
Actually, it uses ECDSA public key.

**Comment by Deltafox79** [comment]
Amazing.. you deobfuscate manually whit ollydbg? or whit patcher? best regards

**Comment by DoubleLabyrinth** [comment]
with patcher.

**Comment by tomatinox** [comment]
could i have the dll to me? TomatoKey@altmails.com

Thank you
